SELECT CONCAT(FLOOR((MONTH(DIFFERENTIATION_DATE) - 1) / 3 + 1), 'Q') AS QUARTER, COUNT(*) as ECOLI_COUNT 
FROM ECOLI_DATA
GROUP BY CONCAT(FLOOR((MONTH(DIFFERENTIATION_DATE) - 1) / 3 + 1), 'Q')
ORDER BY QUARTER;
